name: Arduino_CI

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "src/**"
      - "lib/**"
      - "platformio.ini"
      - ".github/workflows/arduino_ci.yml"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        examples:
          - src/lv_speedometer/main.ino

    env:
      EXAMPLES: ${{matrix.examples}}

    steps:
      - uses: actions/checkout@v3

      - name: Install Arduino Ci
        run: |
          wget https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz -O arduino-cli.tar.gz ;
          sudo tar xf arduino-cli.tar.gz -C /usr/local/bin arduino-cli ;
          arduino-cli config init ;
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json ;
          arduino-cli core update-index ;
          arduino-cli core install esp32:esp32@2.0.14 ;

      - name: Build examples
        run: |
          mkdir -p $HOME/Arduino/libraries ;
          cp  -r $PWD/lib/* $HOME/Arduino/libraries

          cd $GITHUB_WORKSPACE ;
          arduino-cli compile -b esp32:esp32:feathers3 $PWD/$EXAMPLES ;
