name: PlatformIO CI

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "src/**"
      - "lib/**"
      - "platformio.ini"
      - ".github/workflows/platformio.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example:
          - lv_speedometer

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Run PlatformIO
        run: |
          export PLATFORMIO_SRC_DIR="src/${{ matrix.example }}"
          pio run -e  ${{ matrix.example }}
